export const CHECK_API = 'checkapi'
export const HOT_COSTUME = 'api/hotcostume'
export const VIDEOS = 'api/videos'
export const STORIES = 'api/stories'
export const LIST_ARTICLE = 'api/index_article'
export const LIST_CLOTHES = 'api/cloths'
export const LIST_RELATED_CLOTHES = 'api/related_clothes'
export const LIST_PRICE = 'api/index_price'
export const LIST_PHOTOER = 'api/photographers'
export const LIST_NOTI = 'api/notification'
export const SHOW_DETAIL = 'api/show_detail'
export const SHOW_RAND_DETAIL = 'api/show_rand_detail'
export const SHOW_VIEWER = 'api/viewers'
export const SHOW_RAND_EXCEPT = 'api/show_rand_except'
export const SHOW_RELATED_DETAIL = 'api/show_related_detail'
export const LIST_PRODUCTS = 'api/get_products'
export const MAIN_ARTICLE = 'api/get_main_article'
export const GET_LIST_DECORTAION = 'api/get_list_decoration'

export const USER = 'api/USER'

export const SET_USER = 'api/SET_USER'

export const MUTATE_SET_USER = 'api/MUTATE_SET_USER'
